name: Generate GitHub Metrics

on:
  schedule:
    - cron: "10 19 * * *"  # 00:40 IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_display: large
          config_padding: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_habits: yes
          plugin_habits_charts: yes
        continue-on-error: true

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add GitHub_Metrics.svg || true
          git commit -m "chore: update github metrics" || echo "No changes to commit"
          git push origin main || true
