name: Isometric Commit Calendar

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch: # Manual trigger

permissions:
  contents: write # Needed for pushing changes

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # Generate Isometric Commit Calendar
      - name: Generate isocalendar SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: isocalendar.svg
          plugin_isocalendar: yes
          config_timezone: Asia/Kolkata

      # Commit the SVG
      - name: Commit & push isocalendar SVG
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add isocalendar.svg
          git commit -m "chore: update isocalendar metrics" || echo "No changes to commit"
          git push origin main
