name: Generate Isometric Commit Calendar

on:
  schedule:
    - cron: "40 18 * * *"  # 00:10 IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-commit-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Commit Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Isometric_Commit_Calendar.svg
          base: ""
          plugin_isocalendar: yes
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        continue-on-error: true

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add Isometric_Commit_Calendar.svg || true
          git commit -m "chore: update commit calendar" || echo "No changes to commit"
          git push origin main || true
