name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger
  push: {branches: main}
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Personal access token with repo scope
          filename: "metrics/activity.svg"
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_limit: 5
          plugin_activity_filter: all # Show all activity

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/community.svg"
          plugin_community: yes
          plugin_community_limit: 5

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/header.svg"
          plugin_header: yes
          plugin_header_user: iamp1000

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/metadata.svg"
          plugin_metadata: yes

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/repositories.svg"
          plugin_repositories: yes
          plugin_repositories_limit: 5

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/languages.svg"
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_details: percentage

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/habits.svg"
          plugin_habits: yes
          plugin_habits_days: 90
          plugin_habits_facts: 5

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/isocalendar.svg"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
