name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs every day at 00:00 UTC
  workflow_dispatch:              # Allow manual runs
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Kolkata
