name: Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Header SVG
        run: echo "Generating Header SVG..."

      - name: Generate Activity SVG
        run: echo "Generating Activity SVG..."

      - name: Generate Community SVG
        run: echo "Generating Community SVG..."

      - name: Generate Repositories SVG
        run: echo "Generating Repositories SVG..."

      - name: Generate Metadata SVG
        run: echo "Generating Metadata SVG..."

      - name: Commit metrics
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update metrics" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
