name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Every day at midnight UTC
  workflow_dispatch:              # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_habits: yes
          plugin_habits_from: 200       # Days to look back
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata

      - name: Commit metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "update: metrics" || echo "No changes"
          git push
