first name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:     # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for committing and pushing changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checks out your repo so files can be generated and committed

      - name: Generate Header SVG
        uses: lowighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: github-header.svg
          base: header

      - name: Generate Activity SVG
        uses: lowighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: github-activity.svg
          base: activity

      - name: Generate Community SVG
        uses: lowighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: github-community.svg
          base: community

      - name: Generate Repositories SVG
        uses: lowighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: github-repositories.svg
          base: repositories

      - name: Generate Metadata SVG
        uses: lowighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: github-metadata.svg
          base: metadata

      - name: Commit metrics
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-header.svg github-activity.svg github-community.svg github-repositories.svg github-metadata.svg || echo "No files to add"
          git commit -m "update: metrics" || echo "No changes to commit"
          git push || echo "Push failed"
