name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:     # Manual trigger

permissions:
  contents: write       # Needed for pushing commits

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Keep access to GITHUB_TOKEN
          fetch-depth: 0            # Get full commit history

      - name: Generate all SVGs
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          base: header, activity, community, repositories, metadata
          filename: github-metrics.svg
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_habits: yes
          config_timezone: Asia/Kolkata

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add github-metrics.svg
          git commit -m "chore: update metrics" || echo "No changes to commit"
          git push origin main
