name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs every day at 00:00 UTC
  workflow_dispatch:              # Allow manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # ✅ Step 1: Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Step 2: Run metrics
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: github-metrics.svg
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Kolkata

      # ✅ Step 3: Commit metrics back to repo
      - name: Commit metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "chore: update GitHub metrics" || echo "No changes to commit"
          git push
