name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:     # Manual trigger

permissions:
  contents: write        # Needed for pushing changes

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate combined metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_habits: yes
          config_timezone: Asia/Kolkata

      - name: Commit & push metrics
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add metrics.svg
          git commit -m "chore: update metrics" || echo "No changes to commit"
          git push origin main
      - name: Install Inkscape
        run: sudo apt-get update && sudo apt-get install -y inkscape
      - name: Make script executable
        run: chmod +x .scripts/split-metrics.sh
      - name: Run split script
        run: ./.scripts/split-metrics.sh
      - name: Upload split images
        uses: actions/upload-artifact@v4
        with:
          name: split-metrics
          path: .scripts/output/*.svg
      - name: Commit split SVGs
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add github-header.svg github-languages.svg github-community.svg github-repositories.svg github-metadata.svg
          git commit -m "chore: update split metrics" || echo "No changes to commit"
          git push origin mai
