first_name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:     # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for committing and pushing changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Header Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: header-metrics.svg
          base: header
          config_timezone: Asia/Kolkata

      - name: Generate Activity Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: activity-metrics.svg
          base: activity
          plugin_habits: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Kolkata

      - name: Generate Community Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: community-metrics.svg
          base: community
          config_timezone: Asia/Kolkata

      - name: Generate Repository Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: repositories-metrics.svg
          base: repositories
          config_timezone: Asia/Kolkata

      - name: Generate Metadata Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: metadata-metrics.svg
          base: metadata
          config_timezone: Asia/Kolkata

      - name: Commit metrics
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.svg || echo "No file to add"
          git commit -m "update: metrics" || echo "No changes to commit"
          git push || echo "Push failed"
