name: Generate Spotify Playlist Metrics

on:
  schedule:
    - cron: "00 19 * * *"  # 00:30 IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-spotify-playlist-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Spotify Playlist Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Spotify_Playlist_Metrics.svg
          base: ""
          plugin_music: yes
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/embed/playlist/0dYrEddNow6Me8fxR7Zd2w
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.c0f2a78fc98f4ca38425b70b2a54ce11 }}
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        env:
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
        continue-on-error: true

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add Spotify_Playlist_Metrics.svg || true
          git commit -m "chore: update spotify playlist metrics" || echo "No changes to commit"
          git push origin main || true
