name: Spotify Playlist Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate Spotify playlist metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: spotify_playlist.svg
          plugin_music: yes
          plugin_music_playlist: https://open.spotify.com/embed/playlist/0dYrEddNow6Me8fxR7Zd2w
          config_timezone: Asia/Kolkata

      - name: Commit & push Spotify playlist metrics
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add spotify_playlist.svg
          git commit -m "chore: update Spotify playlist metrics" || echo "No changes to commit"
          git push origin main
