name: Update All Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Achievements.svg
          base: ""
          plugin_achievements: yes
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        continue-on-error: true

      - name: Generate Coding Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Coding_Habits.svg
          base: ""
          plugin_habits: yes
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        continue-on-error: true

      - name: Generate Isometric Commit Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Isometric_Commit_Calendar.svg
          base: ""
          plugin_isocalendar: yes
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        continue-on-error: true

      - name: Generate Languages Activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Languages_Activity.svg
          base: ""
          plugin_languages: yes
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        continue-on-error: true

      - name: Generate Leetcode Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Leetcode_Metrics.svg
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: ${{ secrets.LEETCODE_USERNAME }}
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        continue-on-error: true

      - name: Generate Repositories Traffic
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Repositories_Traffic.svg
          base: ""
          plugin_traffic: yes
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        continue-on-error: true

      - name: Generate Spotify Playlist Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Spotify_Playlist_Metrics.svg
          base: ""
          plugin_music: yes
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/playlist/0dYrEddNow6Me8fxR7Zd2w?si=485330a000744f32
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        env:
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
        continue-on-error: true

      - name: Generate Starred Topics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          filename: Starred_Topics.svg
          base: ""
          plugin_topics: yes
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
        continue-on-error: true

      - name: Commit & Push All Metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add *.svg || true
          git commit -m "chore: update all metrics" || echo "No changes to commit"
          git push origin main || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
