name: Update All Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN_SHHH_IT_IS_A_SECRET }}
          config_timezone: Asia/Kolkata
          config_padding: 10
          config_display: large
          outputs: |
            Achievements.svg: plugin_achievements=yes
            Coding_Habits.svg: plugin_habits=yes
            Isometric_Commit_Calendar.svg: plugin_isocalendar=yes
            Languages_Activity.svg: plugin_languages=yes
            Leetcode_Metrics.svg: plugin_leetcode=yes;plugin_leetcode_user=${{ secrets.LEETCODE_USERNAME }}
            Repositories_Traffic.svg: plugin_traffic=yes
            Spotify_Playlist_Metrics.svg: plugin_music=yes;plugin_music_playlist_url=https://open.spotify.com/playlist/0dYrEddNow6Me8fxR7Zd2w?si=485330a000744f32;plugin_music_token=${{ secrets.SPOTIFY_TOKEN }}
            Starred_Topics.svg: plugin_topics=yes
        env:
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        continue-on-error: true
        retry:
          max_attempts: 3
          wait_ms: 1000

      - name: Commit & Push All Metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add *.svg || true
          git commit -m "chore: update all metrics" || echo "No changes to commit"
          git push origin main || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
